[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.fmtcheck]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]

[tasks.check]
dependencies = [
    "fmtcheck",
    "test",
    "lint"
]

[tasks.doc-build]
install_crate = "mdbook"
cwd = "doc"
workspace = false
command = "mdbook"
args = ["build"]
dependencies = ["doc-build-highlighter"]

[tasks.doc-serve]
install_crate = "mdbook"
cwd = "doc"
workspace = false
command = "mdbook"
args = ["serve"]
dependencies = ["doc-build"]

[tasks.doc-nuke]
cwd = "doc"
workspace = false
command = "rm"
args = ["-rf", "book"]

[tasks.doc-build-highlighter]
cwd = "doc"
workspace = false
script = [
    '''
    cp ./leafbuild_highlight.js hl_clone/highlight.js/src/languages/leafbuild.js
    pushd hl_clone || exit $?
    cd highlight.js || exit $?
    node tools/build.js -n leafbuild rust bash || exit $?
    popd || exit $?
    cp hl_clone/highlight.js/build/highlight.js theme/highlight.js || exit $?
    '''
]

[tasks.setup-docs-env]
workspec = false
script = [
    '''
    mkdir -p doc/hl_clone
    git clone https://github.com/highlightjs/highlight.js doc/hl_clone/highlight.js
    cd doc/hl_clone/highlight.js
    npm install
    '''
]

[tasks.clean-docs-env]
workspace = false
script = [
    '''
    rm -rf doc/hl_clone
    '''
]

[tasks.verify-commit-message]
workspace = false
command = "cargo"
args = [
    "run",
    "--package", "leafbuild-ghk",
    "--bin", "verify_commit_message",
    "--",
    # Check for files in the root directory
    "${@}"
]

[tasks.ci-flow]
workspace = false
dependencies = ["check"]
